// Generated by gencpp from file mpu6050/ResetIMU.msg
// DO NOT EDIT!


#ifndef MPU6050_MESSAGE_RESETIMU_H
#define MPU6050_MESSAGE_RESETIMU_H

#include <ros/service_traits.h>


#include <mpu6050/ResetIMURequest.h>
#include <mpu6050/ResetIMUResponse.h>


namespace mpu6050
{

struct ResetIMU
{

typedef ResetIMURequest Request;
typedef ResetIMUResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetIMU
} // namespace mpu6050


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mpu6050::ResetIMU > {
  static const char* value()
  {
    return "093924429c8ce590aa2b41b10a45ad80";
  }

  static const char* value(const ::mpu6050::ResetIMU&) { return value(); }
};

template<>
struct DataType< ::mpu6050::ResetIMU > {
  static const char* value()
  {
    return "mpu6050/ResetIMU";
  }

  static const char* value(const ::mpu6050::ResetIMU&) { return value(); }
};


// service_traits::MD5Sum< ::mpu6050::ResetIMURequest> should match
// service_traits::MD5Sum< ::mpu6050::ResetIMU >
template<>
struct MD5Sum< ::mpu6050::ResetIMURequest>
{
  static const char* value()
  {
    return MD5Sum< ::mpu6050::ResetIMU >::value();
  }
  static const char* value(const ::mpu6050::ResetIMURequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mpu6050::ResetIMURequest> should match
// service_traits::DataType< ::mpu6050::ResetIMU >
template<>
struct DataType< ::mpu6050::ResetIMURequest>
{
  static const char* value()
  {
    return DataType< ::mpu6050::ResetIMU >::value();
  }
  static const char* value(const ::mpu6050::ResetIMURequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mpu6050::ResetIMUResponse> should match
// service_traits::MD5Sum< ::mpu6050::ResetIMU >
template<>
struct MD5Sum< ::mpu6050::ResetIMUResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mpu6050::ResetIMU >::value();
  }
  static const char* value(const ::mpu6050::ResetIMUResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mpu6050::ResetIMUResponse> should match
// service_traits::DataType< ::mpu6050::ResetIMU >
template<>
struct DataType< ::mpu6050::ResetIMUResponse>
{
  static const char* value()
  {
    return DataType< ::mpu6050::ResetIMU >::value();
  }
  static const char* value(const ::mpu6050::ResetIMUResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MPU6050_MESSAGE_RESETIMU_H
