// Generated by gencpp from file polygon_coverage_msgs/PolygonServiceResponse.msg
// DO NOT EDIT!


#ifndef POLYGON_COVERAGE_MSGS_MESSAGE_POLYGONSERVICERESPONSE_H
#define POLYGON_COVERAGE_MSGS_MESSAGE_POLYGONSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace polygon_coverage_msgs
{
template <class ContainerAllocator>
struct PolygonServiceResponse_
{
  typedef PolygonServiceResponse_<ContainerAllocator> Type;

  PolygonServiceResponse_()
    : success(false)  {
    }
  PolygonServiceResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PolygonServiceResponse_

typedef ::polygon_coverage_msgs::PolygonServiceResponse_<std::allocator<void> > PolygonServiceResponse;

typedef boost::shared_ptr< ::polygon_coverage_msgs::PolygonServiceResponse > PolygonServiceResponsePtr;
typedef boost::shared_ptr< ::polygon_coverage_msgs::PolygonServiceResponse const> PolygonServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator1> & lhs, const ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator1> & lhs, const ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace polygon_coverage_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "polygon_coverage_msgs/PolygonServiceResponse";
  }

  static const char* value(const ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response fields:\n"
"bool success # True on success, false on polygon error.\n"
"\n"
;
  }

  static const char* value(const ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PolygonServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::polygon_coverage_msgs::PolygonServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POLYGON_COVERAGE_MSGS_MESSAGE_POLYGONSERVICERESPONSE_H
