// Generated by gencpp from file polygon_coverage_msgs/PolygonService.msg
// DO NOT EDIT!


#ifndef POLYGON_COVERAGE_MSGS_MESSAGE_POLYGONSERVICE_H
#define POLYGON_COVERAGE_MSGS_MESSAGE_POLYGONSERVICE_H

#include <ros/service_traits.h>


#include <polygon_coverage_msgs/PolygonServiceRequest.h>
#include <polygon_coverage_msgs/PolygonServiceResponse.h>


namespace polygon_coverage_msgs
{

struct PolygonService
{

typedef PolygonServiceRequest Request;
typedef PolygonServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PolygonService
} // namespace polygon_coverage_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::polygon_coverage_msgs::PolygonService > {
  static const char* value()
  {
    return "7c41cb26384cf37ba066f9b416bd9391";
  }

  static const char* value(const ::polygon_coverage_msgs::PolygonService&) { return value(); }
};

template<>
struct DataType< ::polygon_coverage_msgs::PolygonService > {
  static const char* value()
  {
    return "polygon_coverage_msgs/PolygonService";
  }

  static const char* value(const ::polygon_coverage_msgs::PolygonService&) { return value(); }
};


// service_traits::MD5Sum< ::polygon_coverage_msgs::PolygonServiceRequest> should match
// service_traits::MD5Sum< ::polygon_coverage_msgs::PolygonService >
template<>
struct MD5Sum< ::polygon_coverage_msgs::PolygonServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::polygon_coverage_msgs::PolygonService >::value();
  }
  static const char* value(const ::polygon_coverage_msgs::PolygonServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::polygon_coverage_msgs::PolygonServiceRequest> should match
// service_traits::DataType< ::polygon_coverage_msgs::PolygonService >
template<>
struct DataType< ::polygon_coverage_msgs::PolygonServiceRequest>
{
  static const char* value()
  {
    return DataType< ::polygon_coverage_msgs::PolygonService >::value();
  }
  static const char* value(const ::polygon_coverage_msgs::PolygonServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::polygon_coverage_msgs::PolygonServiceResponse> should match
// service_traits::MD5Sum< ::polygon_coverage_msgs::PolygonService >
template<>
struct MD5Sum< ::polygon_coverage_msgs::PolygonServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::polygon_coverage_msgs::PolygonService >::value();
  }
  static const char* value(const ::polygon_coverage_msgs::PolygonServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::polygon_coverage_msgs::PolygonServiceResponse> should match
// service_traits::DataType< ::polygon_coverage_msgs::PolygonService >
template<>
struct DataType< ::polygon_coverage_msgs::PolygonServiceResponse>
{
  static const char* value()
  {
    return DataType< ::polygon_coverage_msgs::PolygonService >::value();
  }
  static const char* value(const ::polygon_coverage_msgs::PolygonServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POLYGON_COVERAGE_MSGS_MESSAGE_POLYGONSERVICE_H
