// Generated by gencpp from file imu_msgs/Angle.msg
// DO NOT EDIT!


#ifndef IMU_MSGS_MESSAGE_ANGLE_H
#define IMU_MSGS_MESSAGE_ANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_msgs
{
template <class ContainerAllocator>
struct Angle_
{
  typedef Angle_<ContainerAllocator> Type;

  Angle_()
    : TimeStamp()
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  Angle_(const ContainerAllocator& _alloc)
    : TimeStamp()
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _TimeStamp_type;
  _TimeStamp_type TimeStamp;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::imu_msgs::Angle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_msgs::Angle_<ContainerAllocator> const> ConstPtr;

}; // struct Angle_

typedef ::imu_msgs::Angle_<std::allocator<void> > Angle;

typedef boost::shared_ptr< ::imu_msgs::Angle > AnglePtr;
typedef boost::shared_ptr< ::imu_msgs::Angle const> AngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_msgs::Angle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_msgs::Angle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_msgs::Angle_<ContainerAllocator1> & lhs, const ::imu_msgs::Angle_<ContainerAllocator2> & rhs)
{
  return lhs.TimeStamp == rhs.TimeStamp &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_msgs::Angle_<ContainerAllocator1> & lhs, const ::imu_msgs::Angle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_msgs::Angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_msgs::Angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_msgs::Angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_msgs::Angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_msgs::Angle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_msgs::Angle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_msgs::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "663b245e480fb01f85d7fed608e522b5";
  }

  static const char* value(const ::imu_msgs::Angle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x663b245e480fb01fULL;
  static const uint64_t static_value2 = 0x85d7fed608e522b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_msgs::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_msgs/Angle";
  }

  static const char* value(const ::imu_msgs::Angle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_msgs::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time TimeStamp\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::imu_msgs::Angle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_msgs::Angle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.TimeStamp);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Angle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_msgs::Angle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_msgs::Angle_<ContainerAllocator>& v)
  {
    s << indent << "TimeStamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.TimeStamp);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_MSGS_MESSAGE_ANGLE_H
